export const DEFAULT_POSTS = [
  {
    id: '1',
    title: 'Annual Quran Recitation Championship Results',
    excerpt: 'Our students achieved remarkable results in this year\'s national Quran recitation championship, with three students placing in the top ten.',
    content: `<p>We are delighted to announce the outstanding achievements of our students in the National Quran Recitation Championship held in Cairo this year. Three of our dedicated students placed in the top ten nationally, a testament to the rigorous training and spiritual dedication fostered at our institute.</p><p>The competition drew over 500 participants from across the country. Our head instructor, Sheikh Ibrahim Al-Mansouri, praised the students for their unwavering commitment to mastering proper tajweed rules.</p><p>The championship evaluated participants on their mastery of tajweed, voice quality, memorization accuracy, and the spiritual depth of their recitation. Our students excelled particularly in tajweed accuracy, reflecting months of focused daily practice.</p><p>We extend our heartfelt congratulations to all participating students and thank the families who supported their children throughout this journey.</p>`,
    author: 'Sheikh Ibrahim Al-Mansouri',
    date: '2026-09-15',
    category: 'Achievements',
    image: 'https://images.unsplash.com/photo-1585036156171-384164a8c675?w=800&h=500&fit=crop&auto=format',
    type: 'news',
  },
  {
    id: '2',
    title: 'New Tajweed Department Opens This October',
    excerpt: 'We are expanding our curriculum with a dedicated advanced Tajweed department for students seeking deep mastery of Quranic recitation sciences.',
    content: `<p>This October, the Quran Institute proudly opens its new Advanced Tajweed Department, offering students an unprecedented depth of study in the science of Quranic recitation.</p><p>The department will be headed by Dr. Aisha Karimi, who holds an Ijazah in the Ten Qira'at and has spent fifteen years training students across three continents. The curriculum includes intensive study of the six levels of tajweed, vocal training, and the historical transmission of Quranic recitation.</p><p>Enrollment is open to students who have completed the foundational Quran memorization program. Limited seats are available; interested applicants are encouraged to apply before September 30th.</p>`,
    author: 'Admin Office',
    date: '2026-09-10',
    category: 'Announcements',
    image: 'https://images.unsplash.com/photo-1609599006353-e629aaabfeae?w=800&h=500&fit=crop&auto=format',
    type: 'news',
  },
  {
    id: '3',
    title: 'Ramadan 2026 Special Program Registration Open',
    excerpt: 'Register now for our intensive Ramadan program featuring daily tafsir sessions, night prayers, and community iftar gatherings.',
    content: `<p>The Quran Institute is pleased to announce registration for its Ramadan 2026 Special Program, an immersive spiritual experience designed for Muslims of all backgrounds and levels of Quran knowledge.</p><p>The program runs throughout the holy month and includes daily Fajr recitation circles, afternoon tafsir lectures, evening Quran review sessions, and night Qiyam prayers led by our resident scholars.</p><p>Community iftar gatherings will be hosted three times weekly, fostering brotherhood and sisterhood among participants. The program culminates in a full Quran khatm on the 27th night of Ramadan.</p>`,
    author: 'Programs Committee',
    date: '2026-09-01',
    category: 'Programs',
    image: 'https://images.unsplash.com/photo-1564769662533-4f00a87b4056?w=800&h=500&fit=crop&auto=format',
    type: 'news',
  },
  {
    id: '4',
    title: 'Understanding the Maqasid of Quran Education',
    excerpt: 'A deep reflection on the higher objectives of learning the Quran and how they shape our approach to teaching at the institute.',
    content: `<p>The Quran is not merely a book to be read — it is a complete way of life, a guide for the intellect and a balm for the soul. When we speak of Quran education, we must begin with a clear understanding of its higher objectives, or maqasid.</p><p>The first maqsad of Quran education is tilawah — the correct recitation of the words of Allah as revealed to the Prophet Muhammad ﷺ. This encompasses the science of tajweed, which ensures that the divine words are pronounced with the precision they deserve.</p><p>The second maqsad is hifz — memorization. The Quran has been preserved in the hearts of millions since the time of the Prophet ﷺ, and this oral tradition remains a pillar of Islamic civilization. Every memorizer becomes a living vessel of revelation.</p><p>The third and most expansive maqsad is tadabbur — deep reflection and contemplation of the Quran's meanings, wisdom, and guidance for human life in every era.</p><p>At our institute, we build our curriculum around these three pillars, ensuring that students emerge not only as skilled reciters but as individuals transformed by their encounter with the word of God.</p>`,
    author: 'Dr. Yusuf Al-Hashimi',
    date: '2026-09-12',
    category: 'Education',
    image: 'https://images.unsplash.com/photo-1532153975070-2e9ab71f1b14?w=800&h=500&fit=crop&auto=format',
    type: 'blog',
  },
  {
    id: '5',
    title: 'How Memorizing Quran Shapes the Character of a Child',
    excerpt: 'Research and personal accounts reveal how the journey of hifz builds discipline, patience, and moral excellence in young students.',
    content: `<p>Parents who enroll their children in hifz programs often remark on a transformation that goes far beyond the acquisition of a memorized text. Something deeper happens when a child commits the words of the Quran to memory — a shaping of character that scholars have observed across generations.</p><p>Discipline is perhaps the most visible gift. A child in hifz must wake before dawn, review pages daily, and maintain consistency over years. This builds an interior architecture of perseverance that manifests in every domain of life.</p><p>Patience follows closely. Memorization is not linear — portions that were solid yesterday can slip today. Learning to return without despair, to re-approach the same ayah with fresh humility, teaches children a crucial life skill: resilience in the face of setbacks.</p><p>Perhaps most profoundly, the content itself shapes character. A child who has the descriptions of Paradise and the warnings of accountability woven into their memory carries a moral compass that is always within reach.</p>`,
    author: 'Sr. Fatimah Nour',
    date: '2026-09-05',
    category: 'Parenting & Education',
    image: 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=800&h=500&fit=crop&auto=format',
    type: 'blog',
  },
  {
    id: '6',
    title: 'The Science of Tajweed: A Beginner\'s Guide',
    excerpt: 'An accessible introduction to the rules of Quranic recitation for those beginning their journey with the Quran.',
    content: `<p>Tajweed — from the Arabic root j-w-d meaning "to make something excellent" — is the science governing the correct pronunciation of the Quran. Its rules were never invented; they were derived from the recitation of the Prophet Muhammad ﷺ himself, preserved through a chain of teachers reaching to us today.</p><p>For a beginner, tajweed can feel overwhelming. There are rules for elongation (madd), rules for nasalization (ghunnah), rules for stopping and starting (waqf and ibtida), and dozens of specific pronunciations for individual letters. Where does one begin?</p><p>The answer, experienced teachers unanimously agree, is with the lips and tongue — learning the precise articulation points (makhaarij) of each Arabic letter. This foundation, once properly established, makes all subsequent rules comprehensible and natural.</p><p>At our institute, beginners spend their first month entirely on letter articulation before learning a single tajweed rule. The investment always pays dividends.</p>`,
    author: 'Ustadh Hamza Suleiman',
    date: '2026-08-28',
    category: 'Tajweed',
    image: 'https://images.unsplash.com/photo-1618944913086-3c4b5c3d1a1e?w=800&h=500&fit=crop&auto=format',
    type: 'blog',
  },
];

export const DEFAULT_ADMINS = [
  {
    id: 'admin-1',
    name: 'Super Administrator',
    email: 'admin@quraninstitute.org',
    role: 'super_admin',
    createdAt: '2025-01-01',
    lastLogin: '2026-09-20',
  },
];

